-- 10-1 테이블에 데이터 추가하기
-- DEPT 테이블을 복사해서 DEPT_TEMP 테이블 만들기
CREATE TABLE DEPT_TEMP
	AS SELECT * FROM DEPT;
	
SELECT * FROM DEPT_TEMP;

-- DETP_TEMP 테이블에 데이터 추가하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
			   VALUES (50, 'DATABASE', 'SEOUL');
	
-- INSERT문에 열 지정 없이 데이터 추가하기
INSERT INTO DEPT_TEMP
	VALUES (60, 'NETWORK', 'BUSAN');
	
-- NULL을 지정하여 입력하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
			   VALUES (70, 'WEB', NULL);
			   
-- 빈 공백 문자열로 NULL을 입력하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
			   VALUES (80, 'MOBILE', '');
			  
-- 열 데이터를 넣지 않는 방식으로 NULL 데이터 입력하기
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
			   VALUES (90, 'INCHON');
SELECT * FROM DEPT_TEMP;

-- EMP테이블 복사
CREATE TABLE EMP_TEMP
	AS SELECT *
		 FROM EMP
		WHERE 1 <> 1;

-- INSERT문으로 날짜 데이터 입력하기(날짜 사이에/입력)
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
			  VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 
			  		  5000, 1000, 10);
-- INSERT문으로 날짜 데이터 입력하기(날짜 사이에-입력)
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
			  VALUES (1111, '성춘향', 'MANAGER', 9999, '2001-01-05', 
			  		  4000, NULL, 20);
-- 날짜 데이터 형식을 반대로 했을 때(에러)
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
			  VALUES (2111, '이순신', 'MANAGER', 9999, '07/01/2001', 
			  		  4000, NULL, 20);
-- TO_DATE 함수를 사용하여 날짜 데이터 입력하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
			  VALUES (2111, '이순신', 'MANAGER', 9999, TO_DATE('07/01/2001', 'DD/MM/YYYY'), 
			  		  4000, NULL, 20);
			  		 
-- SYSDATE를 사용하여 날짜 데이터 입력하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
			  VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 
			  		  4000, NULL, 30);
-- 서브쿼리로 여러 데이터 추가하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
	SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
	  FROM EMP E, SALGRADE S
	 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
	   AND S.GRADE = 1;
	  
SELECT * FROM EMP_TEMP;

-- 10-2 테이블에 있는 데이터 수정하기
-- 테이블 복사
CREATE TABLE DEPT_TEMP2
	AS SELECT * FROM DEPT;
DROP TABLE DEPT_TEMP2;
-- DEPT_TEMP2 테이블 업데이트하기
UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL';
 
ROLLBACK;

-- 테이블 데이터 중 일부만 수정하기
UPDATE DEPT_TEMP2
   SET DNAME = 'DATABASE',
   	   LOC = 'SEOUL'
 WHERE DEPTNO = 40;
 
-- 1분 복습
UPDATE EMP_TEMP
   SET COMM = 50
 WHERE SAL <= 2500;

-- 서브쿼리로 데이터 일부분 수정하기
UPDATE DEPT_TEMP2
   SET (DNAME, LOC) = (SELECT DNAME, LOC
   						 FROM DEPT
   						WHERE DEPTNO = 40)
 WHERE DEPTNO = 40;

-- UPDATE문의 WHERE절에 서브쿼리 사용하기
UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL'
 WHERE DEPTNO = (SELECT DEPTNO
 				   FROM DEPT_TEMP2
 				  WHERE DNAME = 'OPERATIONS');

SELECT * FROM DEPT_TEMP2;

-- 10-3 테이블에 있는 데이터 삭제하기
-- 테이블 복사
CREATE TABLE EMP_TEMP2
	AS SELECT * FROM EMP;

-- WHERE절을 사용하여 데이터 일부분만 삭제하기
DELETE FROM EMP_TEMP2
 WHERE JOB = 'MANAGER';

DELETE FROM EMP_TEMP2
 WHERE EMPNO IN(SELECT E.EMPNO
				  FROM EMP_TEMP2 E, SALGRADE S
				 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
				   AND S.GRADE = 3
				   AND DEPTNO = 30);
-- 1분 복습
DELETE FROM EMP_TEMP
 WHERE SAL >= 3000;

-- 테이블에 있는 전체 데이터 삭제하기
DELETE FROM EMP_TEMP2;
SELECT * FROM EMP_TEMP;
SELECT * FROM EMP_TEMP2;

-- 테이블 복사
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

-- Q1
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
				   VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
				   VALUES (60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
				   VALUES (70, 'SELECT', 'INCHEON');
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
				   VALUES (80, 'DML', 'BUNDANG');

-- Q2
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7201, 'TEST_USER1', 'MANAGER', 7788,
				  		  TO_DATE('2016/01/02', 'YYYY/MM/DD'), 4500, NULL, 50);
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7202, 'TEST_USER2', 'CLERK', 7201,
				  		  TO_DATE('2016/02/21', 'YYYY/MM/DD'), 1800, NULL, 50);
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7203, 'TEST_USER3', 'ANALYST', 7201,
				  		  TO_DATE('2016/04/11', 'YYYY/MM/DD'), 3400, NULL, 60);
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201,
				  		  TO_DATE('2016/05/31', 'YYYY/MM/DD'), 2700, 300, 60);
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7205, 'TEST_USER5', 'CLERK', 7201,
				  		  TO_DATE('2016/07/20', 'YYYY/MM/DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7206, 'TEST_USER6', 'CLERK', 7201,
				  		  TO_DATE('2016/09/08', 'YYYY/MM/DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7207, 'TEST_USER7', 'LECTURER', 7201,
				  		  TO_DATE('2016/10/28', 'YYYY/MM/DD'), 2300, NULL, 80);
INSERT INTO CHAP10HW_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
				  VALUES (7208, 'TEST_USER8', 'STUDENT', 7201,
				  		  TO_DATE('2016/03/09', 'YYYY/MM/DD'), 1200, NULL, 80);
-- Q3
UPDATE CHAP10HW_EMP	
   SET DEPTNO = 70
 WHERE SAL > (SELECT AVG(SAL)
				FROM CHAP10HW_EMP
			   WHERE DEPTNO = 50);

SELECT * FROM CHAP10HW_EMP
ORDER BY DEPTNO;

-- Q4
UPDATE CHAP10HW_EMP
   SET DEPTNO = 80,
	   SAL = SAL * 1.1
  WHERE HIREDATE > (SELECT MIN(HIREDATE)
					  FROM CHAP10HW_EMP
					 WHERE DEPTNO = 60);
					
-- Q5
DELETE FROM CHAP10HW_EMP
 WHERE EMPNO IN (SELECT E.EMPNO
					FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
				   WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
					 AND S.GRADE = 5);
					
ROLLBACK;
SELECT * FROM CHAP10HW_EMP;
SELECT * FROM CHAP10HW_DEPT;
SELECT * FROM CHAP10HW_SALGRADE;