SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
  FROM EMP;
 
SELECT *
  FROM EMP
 WHERE UPPER(ENAME) LIKE UPPER('%scott%');

SELECT UPPER(ENAME)
  FROM EMP;
 
SELECT ENAME, LENGTH(ENAME)
  FROM EMP;
  
SELECT ENAME, LENGTH(ENAME)
  FROM EMP
 WHERE	LENGTH(ENAME) >= 5;

SELECT LENGTH('한글'), LENGTHB('한글')
  FROM DUAL;
 
SELECT *
  FROM EMP
 WHERE LENGTH(JOB) >= 6;
 
SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5)
  FROM EMP;
 
SELECT SUBSTR(ENAME,3)
  FROM EMP;

SELECT JOB,
	   SUBSTR(JOB, -LENGTH(JOB)),
	   SUBSTR(JOB, -LENGTH(JOB),2),
	   SUBSTR(JOB, -3)
  FROM EMP;
 
SELECT INSTR('HELLO, ORACLE!', 'L') AS INSTR_1,
	   INSTR('HELLO, ORACLE!', 'L', 5) AS INSTR_2,
	   INSTR('HELLO, ORACLE!', 'L', 2, 2) AS INSTR_3
  FROM DUAL;

SELECT *
  FROM EMP
 WHERE INSTR(ENAME, 'S') > 0;

SELECT *
  FROM EMP
 WHERE ENAME LIKE '%S%';

SELECT '010-1234-5678' AS REPLACE_BEFORE,
	   REPLACE('010-1234-5678', '-', ' ') AS REPLACE_1,
	   REPLACE('010-1234-5678', '-') AS REPLACE_2
  FROM DUAL;	   

 