SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
  FROM EMP;
 
SELECT *
  FROM EMP
 WHERE UPPER(ENAME) LIKE UPPER('%scott%');

SELECT UPPER(ENAME)
  FROM EMP;
 
SELECT ENAME, LENGTH(ENAME)
  FROM EMP;

SELECT ENAME, LENGTH(ENAME)
  FROM EMP
 WHERE	LENGTH(ENAME) >= 5;

SELECT LENGTH('한글'), LENGTHB('한글')
  FROM DUAL;
 
SELECT *
  FROM EMP
 WHERE LENGTH(JOB) >= 6;
 
SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5)
  FROM EMP;
 
SELECT SUBSTR(ENAME,3)
  FROM EMP;

SELECT JOB,
	   SUBSTR(JOB, -LENGTH(JOB)),
	   SUBSTR(JOB, -LENGTH(JOB),2),
	   SUBSTR(JOB, -3)
  FROM EMP;
 
SELECT INSTR('HELLO, ORACLE!', 'L') AS INSTR_1,
	   INSTR('HELLO, ORACLE!', 'L', 5) AS INSTR_2,
	   INSTR('HELLO, ORACLE!', 'L', 2, 2) AS INSTR_3
  FROM DUAL;

SELECT *
  FROM EMP
 WHERE INSTR(ENAME, 'S') > 0;

SELECT *
  FROM EMP
 WHERE ENAME LIKE '%S%';

SELECT '010-1234-5678' AS REPLACE_BEFORE,
	   REPLACE('010-1234-5678', '-', ' ') AS REPLACE_1,
	   REPLACE('010-1234-5678', '-') AS REPLACE_2
  FROM DUAL;	   

SELECT 'Oracle',
	   LPAD('Oracle', 10, '#') AS LPAD_1,
	   RPAD('Oracle', 10, '*') AS RPAD_1,
	   LPAD('Oracle', 10) AS LPAD_2,
	   RPAD('Oracle', 10) AS RPAD_2
  FROM DUAL;
  
SELECT RPAD('971225-', 14, '*') AS RPAD_JMNO,
	   RPAD('010-1234-', 13, '*') AS RPAD_PHONE
  FROM DUAL;
 
SELECT CONCAT(EMPNO, ENAME),
	   CONCAT(EMPNO, CONCAT(' : ', ENAME))
  FROM EMP;
  
SELECT EMPNO || ENAME,
	   EMPNO || ' : ' || ENAME
  FROM EMP;
 
SELECT '[' || TRIM(' _ _Oracle_ _ ') || ']' AS TRIM,
	   '[' || TRIM(LEADING FROM ' _ _Oracle_ _ ') || ']' AS TRIM_LEADING,
	   '[' || TRIM(TRAILING FROM ' _ _Oracle_ _ ') || ']' AS TRIM_TRAILING,
	   '[' || TRIM(BOTH FROM ' _ _Oracle_ _ ') || ']' AS TRIM_BOTH
  FROM DUAL;
 
SELECT '[' || TRIM('_' FROM '_ _Oracle_ _') || ']' AS TRIM,
	   '[' || TRIM(LEADING '_' FROM '_ _Oracle_ _') || ']' AS TRIM_LEADING,
	   '[' || TRIM(TRAILING '_' FROM '_ _Oracle_ _') || ']' AS TRIM_TRAILING,
	   '[' || TRIM(BOTH '_' FROM '_ _Oracle_ _') || ']' AS TRIM_BOTH
  FROM DUAL;

 SELECT '[' || TRIM(' _Oracle_ ') || ']' AS TRIM,
	   '[' || LTRIM(' _Oracle_ ') || ']' AS LTRIM_1,
	   '[' || LTRIM('<_Oracle_>', '_<') || ']' AS LTRIM_2,
	   '[' || RTRIM(' _Oracle_ ') || ']' AS RTRIM,
	   '[' || RTRIM('<_Oracle_>', '>_') || ']' AS TRIM_2
  FROM DUAL;

-- 06-3 숫자 함수
-- ROUND
SELECT ROUND(1234.5678) AS ROUND,
	   ROUND(1234.5678, 0) AS ROUND_0,
	   ROUND(1234.5678, 1) AS ROUND_1,
	   ROUND(1234.5678, 2) AS ROUND_2,
	   ROUND(1234.5678, -1) AS ROUND_MINUS1,
	   ROUND(1234.5678, -2) AS ROUND_MINUS
  FROM DUAL;

-- TRUNC
SELECT TRUNC(1234.5678) AS TRUNC,
	   TRUNC(1234.5678, 0) AS TRUNC_0,
	   TRUNC(1234.5678, 1) AS TRUNC_1,
	   TRUNC(1234.5678, 2) AS TRUNC_2,
	   TRUNC(1234.5678, -1) AS TRUNC_MINUS1,
	   TRUNC(1234.5678, -2) AS TRUNC_MINUS
  FROM DUAL;

-- CEIL
SELECT CEIL(3.14),
	   FLOOR(3.14),
	   CEIL(-3.14),
	   FLOOR(-3.14)
  FROM DUAL;

-- MOD
SELECT MOD(15,6),
	   MOD(10,2),
	   MOD(11,2)
  FROM DUAL;

-- 06-4 데이트 함수
-- SYSDATE
SELECT SYSDATE AS NOW,
	   SYSDATE-1 AS YESTERDAY,
	   SYSDATE+1 AS TOMORROW
  FROM DUAL;
 
-- ADD_MONTHS
SELECT SYSDATE,
	   ADD_MONTHS(SYSDATE, 3)
  FROM DUAL;
  
SELECT EMPNO, ENAME, HIREDATE,
	   ADD_MONTHS(HIREDATE, 120) AS WORK10YEAR
  FROM EMP;
  
SELECT EMPNO, ENAME
	   HIREDATE, SYSDATE
  FROM EMP
 WHERE ADD_MONTHS(HIREDATE, 500) > SYSDATE;

SELECT SYSDATE AS TODAY,
	   ADD_MONTHS(SYSDATE, 6) AS AFTER_6
  FROM DUAL;
 
-- MONTHS_BETWEEN
SELECT EMPNO, ENAME, HIREDATE, SYSDATE,
	   MONTHS_BETWEEN(HIREDATE, SYSDATE) AS MONTHS1,
	   MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTHS2,
	   TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTHS3
  FROM EMP;
 
-- NEXT_DAY, LAST_DAY 
SELECT SYSDATE,
	   NEXT_DAY(SYSDATE, '월요일'),
	   LAST_DAY(SYSDATE)
  FROM DUAL;
 
SELECT SYSDATE,
	   ROUND(SYSDATE, 'CC') AS FORMAT_CC,
	   ROUND(SYSDATE, 'YYYY') AS FORMAT_YYYY,
	   ROUND(SYSDATE, 'Q') AS FORMAT_Q,
	   ROUND(SYSDATE, 'DDD') AS FORMAT_DDD,
	   ROUND(SYSDATE, 'HH') AS FORMAT_HH
  FROM DUAL;

SELECT SYSDATE,
	   TRUNC(SYSDATE, 'CC') AS FORMAT_CC,
	   TRUNC(SYSDATE, 'YYYY') AS FORMAT_YYYY,
	   TRUNC(SYSDATE, 'Q') AS FORMAT_Q,
	   TRUNC(SYSDATE, 'DDD') AS FORMAT_DDD,
	   TRUNC(SYSDATE, 'HH') AS FORMAT_HH
  FROM DUAL;
 
-- 06-5 변환함수
SELECT EMPNO, ENAME, EMPNO + '500'
  FROM EMP;

SELECT 'ABCD' + EMPNO, EMPNO
  FROM EMP;
 
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간
  FROM DUAL;
 
SELECT SYSDATE,
	   TO_CHAR(SYSDATE, 'MM') AS MM,
	   TO_CHAR(SYSDATE, 'MON') AS MON,
	   TO_CHAR(SYSDATE, 'MONTH') AS MONTH,
	   TO_CHAR(SYSDATE, 'DD') AS DD,
	   TO_CHAR(SYSDATE, 'DY') AS DY,
	   TO_CHAR(SYSDATE, 'DAY') AS DAY
  FROM DUAL;
 
SELECT SYSDATE,
	   TO_CHAR(SYSDATE, 'MM') AS MM,
       TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = KOREAN') AS MON_KOR,
	   TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = JAPANESE') AS MON_JPN,
	   TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = ENGLISH') AS MON_ENG,
	   TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = KOREAN') AS MONTH_KOR,
	   TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = APANESE') AS MONTH_JPN,
	   TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = ENGLISH') AS MONTH_ENG
  FROM DUAL;
